server:
  port: 11001 # 服务器端口

spring:
  application:
    name: turbine-server # 微服务名称

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/ # 治理客户端服务域
    instance:
      prefer-ip-address: true

turbine:
  appConfig: app-server #要监控的hystrix服务，逗号隔开
  clusterNameExpression: "'default'"

#dashboard暴露所有断点
management:
  endpoints:
    web:
      exposure:
        include: '*'