server:
  port: 8200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/ # 治理客户端服务域

spring:
  application:
    name: app-gateway


  #限流（限流-令牌桶RequestRateLimiter）使用
  redis:
    host: localhost
    port: 6379
    database: 0


  cloud:
    gateway: #springcloudgateway配置
      routes: #路由（数组）
        # 路由1，产品微服务别名
        - id: serviceProduce
          uri: lb://service-product #微服务名称
          predicates: #断言（数组）
          - Path=/productRestController/** #需满足此请求路径
          - Method=GET #需满足GET请求方法
          - Before=2030-10-25T21:28:47.789+08:00 # 需要Before的时间前才能执行
          - After=2020-10-25T21:28:47.789+08:00 # 需要After的时间后才能执行
          filters: #filters带有s，丢了就无效
          - name: RequestRateLimiter #限流-令牌桶，使用redis+Lua实现
            args:
              key-resolver: '#{@pathKeyResolver}' #使用SpEL从SpringIoC容器中获取对象
              #key-resolver: '#{@ipKeyResolver}'
              #key-resolver: '#{@userIdKeyResolver}'
              redis-rate-limiter.replenishRate: 1 #令牌同每秒填充平均速率
              redis-rate-limiter.burstCapacity: 2 #令牌桶的上限

        # 路由2，用户微服务别名
        - id: serviceUser
          uri: lb://service-user
          predicates:
          - Path=/userRestController/**