server:
  port: 8001 # 服务器端口

spring:
  application:
    name: app-server # 微服务名称
  mvc: #定义视图解析器的规则
    view:
      prefix: classpath:/templates/ #文件前缀，templates是thymeleafd的默认路径
      suffix: .html #文件后缀

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/ # 治理客户端服务域

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 2000   #负载均衡超时时间，默认值5000  # 超过则会断路
  ConnectTimeout: 1000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1
service-user: #微服务名称
  ribbon:
    #负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #以轮询的方式进行负载均衡
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机策略
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #重试策略
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #权重策略
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #最佳策略
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule #可用过滤策略
service-product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true #在feign中开启hystrix熔断
  compression:
    response:
      enabled: true # 开启响应压缩
    request:
      enabled: true # 开启请求压缩
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
  client:
    config:
      service-product:
        loggerLevel: FULL # 配置Feign的日志级别，相当于代码配置方式中的Logger
        #loggerLevel: NONE # 不记录任何日志，适用于生成
logging:
  level:
    com.zyf.appserver.product.ProductService: debug #Feign的日志




# 断路器
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #断路器超时时间，默认1000ms # 注意：与ribbon.ReadTimeout谁小谁生效