spring:
  application:
    name: service-user #微服务名称
  profiles:
    active: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/ # 治理客户端服务域

---
spring:
  profiles: 9001
server:
  port: 9001 # 服务器端口
---
spring:
  profiles: 9002
server:
  port: 9002
---
spring:
  profiles: 9003
server:
  port: 9003