server:
  port: 8300

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/ # 治理客户端服务域

spring:
  application:
    name: app-gateway-sentinel
  cloud:
    gateway: #springcloudgateway配置
      routes: #路由（数组）
        # 路由1，产品微服务id
        - id: serviceProduct
          uri: lb://service-product #微服务名称
          predicates: #断言（数组）
          - Path=/productRestController/** #需满足此请求路径
        # 路由2，用户微服务id
        - id: serviceUser
          uri: lb://service-user
          predicates:
          - Path=/userRestController/**